#!/bin/bash

cd /var/www

echo "Installing Magento..."

bin/magento setup:install \
    --db-host=db \
    --db-name=$MYSQL_DATABASE \
    --db-user=$MYSQL_USER \
    --db-password=$MYSQL_PASSWORD \
    --base-url=$MAGE_HOST \
    --base-url-secure=$MAGE_HOST \
    --admin-firstname="${MAGE_ADMIN_FIRSTNAME:-Joe}" \
    --admin-lastname="${MAGE_ADMIN_LASTNAME:-Bloggs}" \
    --admin-email=${MAGE_ADMIN_EMAIL:-magento@wearejh.com} \
    --admin-user=${MAGE_ADMIN_USER:-admin} \
    --admin-password=${MAGE_ADMIN_PASS:-password123} \
    --backend-frontname=${MAGE_BACKEND_FRONTNAME:-admin} \
    --language=${MAGE_LANG:-en_GB} \
    --currency=${MAGE_CURRENCY:-GBP} \
    --timezone=${MAGE_TIMEZONE:-Europe/London} \
    --use-secure=1 \
    --use-secure-admin=1 \
    --cleanup-database -vvv \
    || { exit 1; }

bin/magento index:reindex && \
bin/magento dev:source-theme:deploy --area="adminhtml" --theme="Magento/backend" css/styles-old css/styles && \
bin/magento dev:source-theme:deploy --theme="Magento/blank" css/styles-m css/styles-l css/email css/email-inline && \
bin/magento dev:source-theme:deploy && \
bin/magento setup:static-content:deploy

echo "Installation complete  ᕦ( ̿ ̿ - ̿ ̿ )つ"
