version: '2'
volumes:
  db-data:

services:

  caddy:
    container_name: "m2run__${M2RUN_CONTEXT_NAME}__caddy"
    image: "m2run__${M2RUN_CONTEXT_NAME}__caddy:latest"
    links:
      - entry
    ports:
      - '80:80'
      - '443:443'

  entry:
    container_name: "m2run__${M2RUN_CONTEXT_NAME}__nginx"
    image: bluestreak/entry:3
    volumes_from:
      - php
    depends_on:
      - php

  php:
    container_name: "m2run__${M2RUN_CONTEXT_NAME}__php"
    image: "m2run__${M2RUN_CONTEXT_NAME}__php:latest"
#    volumes:
#      - ./composer.lock:/var/www/composer.lock
#      - ./composer.json:/var/www/composer.json
#      - ./app/code:/var/www/app/code
#      - ./app/design:/var/www/app/design
#      - ./app/code/Magento/Theme:/var/www/app/code/Magento/Theme
    ports:
      - '9000'
    depends_on:
      - db
    environment:
      - HTTPS=on
      - MYSQL_DATABASE=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=docker

      - MAGE_HOST=https://contrib.m2
      - MAGE_ADMIN_USER=admin
      - MAGE_ADMIN_PASS=password123

      - PHP_MEMORY_LIMIT=3G
      - VIRTUAL_HOST=https://contrib.m2
  db:
    container_name: "m2run__${M2RUN_CONTEXT_NAME}__mysql"
    image: 'mysql:5.6'
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=docker
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '3306:3306'

  redis:
    container_name: "m2rum__${M2RUN_CONTEXT_NAME}__redis"
    image: 'redis:3-alpine'
    ports:
      - '6379'

